trigger:
  branches:
    include:
      - developer

jobs:
  - job: macOS_CI_Tests
    displayName: MacOS CI Tests
    pool:
      vmImage: xcode9-macos10.13
    strategy:
      matrix:
        node_14_x:
          node_version: 14.x
    steps:
      - script: npm install -g yarn
      - template: ./daruk.yml


  - job: ubuntu_CI_Tests
    displayName: Ubuntu  CI Tests
    pool:
      vmImage: ubuntu-16.04
    strategy:
      matrix:
        node_14_x:
          node_version: 14.x

    steps:
      - script: sudo apt-get install yarn
      - template: ./daruk.yml

  - job: windows_CI_Tests
    displayName: Windows  CI Tests
    pool:
      vmImage: vs2017-win2016
    strategy:
      matrix:
         node_14_x:
          node_version: 14.x

    steps:
      - script: choco install yarn
      - template: ./daruk.yml
